apiVersion: privatecloud.mendix.com/v1alpha1
kind: MendixApp
metadata:
  name: pib-configurator
spec:
  database: # Specification of Database CR
    servicePlan: {{ .Values.pibConfiguratorApp.database.servicePlan }}
  storage: # Specification of Storage CR
    servicePlan: {{ .Values.pibConfiguratorApp.storage.servicePlan }}
  mendixRuntimeVersion: 9.22.0.62233 # Mendix version to use for placeholder runtime image
  sourceURL: https://github.com/mendix/pib/raw/main/resources/PIBConfigurator/PIBConfigurator_1.0.0.92.mda # URL of App's source MDA
  appURL: {{ .Values.pibConfiguratorApp.appURL }} # URL to access the app
  tls: # Optional, can be omitted : set a custom TLS configuration, overriding the default operator configuration
    # Enable or disable TLS for the app
    enableTLS: true    
  replicas: 1 # Number of replicas, set to 0 to stop all replicas
  runtimeDeploymentPodAnnotations: # Optional, can be omitted : set custom annotations for Mendix Runtime Pods
    # example: inject the Linkerd proxy sidecar
    linkerd.io/inject: enabled
  runtime: # Configuration of the Mendix Runtime
    logAutosubscribeLevel: INFO # Default logging level
    mxAdminPassword: {{ .Values.pibConfiguratorApp.mxAdminPassword }} # base64 encoded password for MendixAdmin user. In this example, 'Welc0me!'; can be left empty keep password unchanged
    dtapMode: P # Security & runtime mode: P for production, D for development
    logLevels: # Optional, can be omitted : set custom log levels for specific nodes
      NodeOne: CRITICAL
      NodeTwo: DEBUG
    microflowConstants: # Optional, can be omitted : set values for microflow constants
      PIBConfigurator.ServerBaseUrl: "http://pibserver/auth/"
      PIBConfigurator.AdminClientID: "admin-cli"
      PIBConfigurator.Username: {{ .Values.pibServer.admin.username }}
      PIBConfigurator.Password: {{ .Values.pibServer.admin.password }}
      PIBConfigurator.Realm: "pib-realm"
      PIBConfigurator.LogNode: "PIBConfigurator"
      Administration.EnableMendixSSOUserMigration: "False"
      NanoflowCommons.Nanoflow_Commons_Version: "2.1.0"
      WebActions.WebActions_Version: "2.4.0"
    scheduledEventExecution: NONE # Optional, can be omitted: specify which scheduled events should be enabled: ALL/NONE/SPECIFIED
    # Mendix Runtime Jetty options, in JSON format; validated and applied by the mx-m2ee-sidecar container
    jettyOptions: |-
      {
        "max_form_content_size": 10485760,
        "use_blocking_connector": false
      }         
